# Generated by Django 5.2.11 on 2026-02-23 14:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('light', 'Light Jet'), ('midsize', 'Midsize Jet'), ('super_midsize', 'Super Midsize Jet'), ('heavy', 'Heavy Jet'), ('ultra_long', 'Ultra Long Range'), ('vip_airliner', 'VIP Airliner')], max_length=30)),
                ('passenger_capacity', models.PositiveIntegerField()),
                ('range_km', models.PositiveIntegerField(help_text='Range in kilometers')),
                ('cruise_speed_kmh', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('image_url', models.URLField(blank=True)),
                ('hourly_rate_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=30)),
                ('origin_description', models.CharField(help_text="E.g. 'New York area' or 'JFK'", max_length=300)),
                ('destination_description', models.CharField(max_length=300)),
                ('approximate_date', models.CharField(blank=True, max_length=100)),
                ('passenger_count', models.PositiveIntegerField(default=1)),
                ('preferred_aircraft_category', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yacht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size_category', models.CharField(choices=[('small', 'Small (under 30m)'), ('medium', 'Medium (30-50m)'), ('large', 'Large (50-80m)'), ('superyacht', 'Superyacht (80m+)')], max_length=20)),
                ('length_meters', models.DecimalField(decimal_places=2, max_digits=6)),
                ('guest_capacity', models.PositiveIntegerField()),
                ('crew_count', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('image_url', models.URLField(blank=True)),
                ('daily_rate_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('home_port', models.CharField(max_length=200)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('trip_type', models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip'), ('multi_leg', 'Multi-Leg')], default='one_way', max_length=20)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('passenger_count', models.PositiveIntegerField()),
                ('special_requests', models.TextField(blank=True)),
                ('catering_requested', models.BooleanField(default=False)),
                ('ground_transport_requested', models.BooleanField(default=False)),
                ('concierge_requested', models.BooleanField(default=False)),
                ('quoted_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('inquiry', 'Inquiry'), ('quoted', 'Quoted'), ('confirmed', 'Confirmed'), ('in_flight', 'In Flight'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='inquiry', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.aircraft')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='flights.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='flights.airport')),
            ],
        ),
        migrations.CreateModel(
            name='FlightLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg_number', models.PositiveIntegerField()),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='flights.flightbooking')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leg_arrivals', to='flights.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leg_departures', to='flights.airport')),
            ],
            options={
                'ordering': ['leg_number'],
            },
        ),
        migrations.CreateModel(
            name='LeaseInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('asset_type', models.CharField(choices=[('aircraft', 'Aircraft'), ('yacht', 'Yacht')], max_length=20)),
                ('lease_duration', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('multi_year', 'Multi-Year')], max_length=20)),
                ('preferred_start_date', models.DateField()),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('usage_description', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.aircraft')),
                ('yacht', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.yacht')),
            ],
        ),
        migrations.CreateModel(
            name='YachtCharter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('departure_port', models.CharField(max_length=200)),
                ('destination_port', models.CharField(blank=True, max_length=200)),
                ('charter_start', models.DateField()),
                ('charter_end', models.DateField()),
                ('guest_count', models.PositiveIntegerField()),
                ('itinerary_description', models.TextField(blank=True)),
                ('special_requests', models.TextField(blank=True)),
                ('quoted_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('inquiry', 'Inquiry'), ('quoted', 'Quoted'), ('confirmed', 'Confirmed'), ('active', 'Active Charter'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='inquiry', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('yacht', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.yacht')),
            ],
        ),
    ]
