# Generated by Django 5.2.11 on 2026-02-24 09:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirCargoInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('contact_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('cargo_type', models.CharField(choices=[('general', 'General Cargo'), ('perishables', 'Perishables / Fresh Produce'), ('pharma', 'Pharmaceuticals / Medical'), ('dangerous_goods', 'Dangerous Goods (DG)'), ('live_animals', 'Live Animals'), ('artwork', 'Artwork / High Value'), ('automotive', 'Automotive / Vehicles'), ('oversized', 'Oversized / Heavy Lift'), ('humanitarian', 'Humanitarian / Aid'), ('other', 'Other')], max_length=30)),
                ('cargo_description', models.TextField()),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dimensions', models.CharField(blank=True, help_text='L x W x H in cm', max_length=200)),
                ('origin_description', models.CharField(max_length=300)),
                ('destination_description', models.CharField(max_length=300)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('urgency', models.CharField(choices=[('standard', 'Standard (3-5 days)'), ('express', 'Express (24-48 hrs)'), ('critical', 'Critical / AOG (same day)')], default='standard', max_length=20)),
                ('is_hazardous', models.BooleanField(default=False)),
                ('requires_temperature_control', models.BooleanField(default=False)),
                ('insurance_required', models.BooleanField(default=False)),
                ('customs_assistance_needed', models.BooleanField(default=False)),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AircraftSalesInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('contact_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('inquiry_type', models.CharField(choices=[('buy', 'Looking to Buy'), ('sell', 'Looking to Sell'), ('trade', 'Trade / Part Exchange'), ('valuation', 'Valuation Only')], max_length=20)),
                ('preferred_category', models.CharField(blank=True, max_length=30)),
                ('preferred_make_model', models.CharField(blank=True, max_length=200)),
                ('budget_range', models.CharField(blank=True, choices=[('under_2m', 'Under $2M'), ('2m_5m', '$2M – $5M'), ('5m_15m', '$5M – $15M'), ('15m_30m', '$15M – $30M'), ('30m_60m', '$30M – $60M'), ('over_60m', 'Over $60M'), ('not_disclosed', 'Prefer not to say')], max_length=20)),
                ('new_or_pre_owned', models.CharField(choices=[('new', 'New'), ('pre_owned', 'Pre-Owned'), ('either', 'Either')], default='either', max_length=20)),
                ('aircraft_make', models.CharField(blank=True, max_length=100)),
                ('aircraft_model', models.CharField(blank=True, max_length=100)),
                ('year_of_manufacture', models.PositiveIntegerField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('total_flight_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('asking_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('support', 'Customer Support'), ('media', 'Media & Press'), ('partnership', 'Partnership'), ('careers', 'Careers'), ('other', 'Other')], default='general', max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupCharterInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('contact_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('group_type', models.CharField(choices=[('corporate', 'Corporate / Business'), ('sports_team', 'Sports Team'), ('entertainment', 'Entertainment / Film'), ('incentive', 'Incentive Group'), ('wedding', 'Wedding Party'), ('government', 'Government / Diplomatic'), ('other', 'Other')], max_length=30)),
                ('group_size', models.PositiveIntegerField()),
                ('origin_description', models.CharField(max_length=300)),
                ('destination_description', models.CharField(max_length=300)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('is_round_trip', models.BooleanField(default=False)),
                ('preferred_aircraft_category', models.CharField(blank=True, max_length=30)),
                ('catering_required', models.BooleanField(default=False)),
                ('ground_transport_required', models.BooleanField(default=False)),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
