# Generated by Django 5.2.11 on 2026-02-25 07:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('to_email', models.EmailField(max_length=254)),
                ('to_name', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('inquiry_type', models.CharField(choices=[('flight_booking', 'Flight Booking'), ('yacht_charter', 'Yacht Charter'), ('lease_inquiry', 'Lease Inquiry'), ('flight_inquiry', 'Flight Inquiry'), ('contact', 'Contact'), ('group_charter', 'Group Charter'), ('air_cargo', 'Air Cargo'), ('aircraft_sales', 'Aircraft Sales'), ('marketplace_booking', 'Marketplace Booking'), ('general', 'General')], default='general', max_length=30)),
                ('related_id', models.IntegerField(blank=True, help_text='PK of the related inquiry/booking', null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_msg', models.TextField(blank=True)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
