# Generated by Django 5.2.11 on 2026-03-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbooking',
            name='commission_pct',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Platform commission % applied at time of confirmation', max_digits=5),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='commission_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Platform earnings = quoted_price × commission_pct / 100', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='net_revenue_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Remainder after commission (goes to ops / crew)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='quoted_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total price quoted to the client', max_digits=12, null=True),
        ),
    ]
